### ISSUE TITLE
Multi user support with Soju?

### ISSUE THREAD

**Issue by poVoq** [progval/matrix2051#31]
More of a question, would it be possible to run this behind a Soju bouncer so that multiple remote users can access via IRC?

See:
https://git.sr.ht/~emersion/soju

**Comment by progval** [comment]
Why not connect multiple IRC clients directly to Matrix2051? They don't even have to use the same instance, as Matrix is natively multi-client

**Comment by poVoq** [comment]
No TLS support etc. From your readme it seems like that is a discouraged and untested use-case, no?

**Comment by progval** [comment]
yes, but using Soju won't change anything, the connection would be plaintext between Soju and Matrix2051 instead of being plaintext between your client and Matrix2051

**Comment by poVoq** [comment]
Sure, but if Matrix2051 and Soju runs on the same server, with no direct outside access to Matrix2051, that would not be a big issue I think?

**Comment by progval** [comment]
Sure, but you can also run Matrix2051 on the same host as your IRC client.

Anyway you can use Soju if you want to and I'll try to fix bugs that might arise from this, but that sounds like an unnecessary complication

**Comment by poVoq** [comment]
> Sure, but you can also run Matrix2051 on the same host as your IRC client.

How would that work if multiple remote users want to access Matrix via IRC?

**Comment by progval** [comment]
yes; Matrix2051 simply pretends to be an independent Matrix "device" for every IRC client connected to it

**Comment by poVoq** [comment]
So a simple stunnel in front of it would also work for remote access of IRC clients?

**Comment by progval** [comment]
it should, yes

**Comment by poVoq** [comment]
ok thanks!

**Comment by Thaodan** [comment]
> Why not connect multiple IRC clients directly to Matrix2051? They don't even have to use the same instance, as Matrix is natively multi-client

You can connect the bouncer to Matrix2051 and then all clients to the bouncer for shared backlog but doing so doesn't require any changes in Matrix2051.
Also the TLS issue is covered by the bouncer in this case since it will act as a proxy.

**Comment by poVoq** [comment]
yes that was the idea behind using Soju.

**Comment by Thaodan** [comment]
> yes; Matrix2051 simply pretends to be an independent Matrix "device" for every IRC client connected to it

How good is Matrix2051 in fending of attackers? I rather connect a bouncer to the internet that knows defend itself plus fail2ban than just matrix2051 plus stunnel.

**Comment by Thaodan** [comment]
If you want to run mutiple instances you can convert the systemd unit to matrix2051@.service and use the name after the @ for each connection to e.g. a different homeserver.

**Comment by progval** [comment]
> How good is Matrix2051 in fending of attackers? I rather connect a bouncer to the internet that knows defend itself plus fail2ban than just matrix2051 plus stunnel.

True. Setting up a bouncer is overkill for this; but if you already have one then it's fine.

> If you want to run mutiple instances you can convert the systemd unit to [matrix2051@.service](mailto:matrix2051@.service) and use the name after the @ for each connection to e.g. a different homeserver.

Internally, Matrix2051 uses completely independent BEAM processes for each client, so this shouldn't matter (unless there are bugs, of course)

**Comment by Thaodan** [comment]
> > How good is Matrix2051 in fending of attackers? I rather connect a bouncer to the internet that knows defend itself plus fail2ban than just matrix2051 plus stunnel.
> 
> True. Setting up a bouncer is overkill for this; but if you already have one then it's fine.
> 
> > If you want to run mutiple instances you can convert the systemd unit to [matrix2051@.service](mailto:matrix2051@.service) and use the name after the @ for each connection to e.g. a different homeserver.
> 
> Internally, Matrix2051 uses completely independent BEAM processes for each client, so this shouldn't matter (unless there are bugs, of course)

Which process starts the new BEAM instance? I noticed that for me only one beam process exists even when I connect to another network.

**Comment by progval** [comment]
"BEAM process" refers to what you would call a green/light thread or coroutine in other environments. All BEAM processes in a single BEAM VM/interpreter show up as a single UNIX process.
