### ISSUE TITLE
Various issues with circe

### ISSUE THREAD

**Issue by Thaodan** [progval/matrix2051#51]
I noticed this issue when connecting with emacs-circe:

```
Arguments are either of the two:

:<server> 333 <target> <channel> <nick> 1434996762
:<server> 333 <target> <channel> <nick>!<user>@<host> 1434996803" (let ((channel-buffer (circe-server-get-chat-buffer channel)) (topic-time (string-to-number topic-time))) (save-current-buffer (set-buffer (or channel-buffer (circe-server-last-active-buffer))) (circe-display (if channel-buffer 'circe-format-server-topic-time 'circe-format-server-topic-time-for-channel) :nick target :channel channel :setter (irc-userstring-nick setter) :setter-userhost (or (irc-userstring-userhost setter) "(unknown)") :topic-time topic-time :topic-date (current-time-string (seconds-to-time topic-time)) :topic-ago (circe-duration-string (- (float-time) topic-time)))))) 6) (args were (#<process  bnc.server.de<1>> "333" "server." "matrixserver" "channel" "0"))
Error running event nil handler circe--irc-display-event: (wrong-number-of-arguments ((circe-query-mode-abbrev-table circe-query-mode-syntax-table circe-channel-mode-abbrev-table circe-channel-mode-syntax-table circe-chat-mode-abbrev-table circe-chat-mode-syntax-table circe-server-mode-abbrev-table circe-server-mode-syntax-table circe-mode-abbrev-table circe-mode-syntax-table t) (_server ignored _numeric target channel setter topic-time) "Show a 333 numeric (RPL_TOPICWHOTIME).
```

I think this is what makes circe disconnect periodically.

Is there something with `RPL_TOPICWHOTIME`?

**Comment by progval** [comment]
I don't see what the issue might be. On Inspircd:

```
:dookie.interlinked.me 333 val #matrix2051 val!~val@Interlinked-5h67cb.mie8.6fm1.hia12b.IP :1635348870
```

and on M51:

```
:server. 333 mynick:example.com #test1:example.org nick:example.org :1633176350
```

The only difference I see is that M51 uses a simple nick instead of the NUH, but emacs-circe explicitly mentions both syntaxes...

**Comment by Thaodan** [comment]
For some reason the order is wrong. Can you check if it because of the
Pantalaimon patch?

For me the order is here:
333 server. nick channel 0

**Comment by progval** [comment]
I don't see how that's possible, this numeric is generated like every other. I'm guessing circe messes with it before printing. Could you check with tcpdump?

**Comment by Thaodan** [comment]
:server. 333 user:matrix.serer.com #channel:matrix.server.com
user:matrix.server.com 1605608377

There was only one such request in tcpdump which is quite strange.

It could be that this caused by the frequent disconnects.

**Comment by Thaodan** [comment]
On Communi I noticed that for some channels the person that sets the status is 0, these were also the channels not includes the channels that I didn't found in tcpdump.

The topic here is simply "<channel> topic was <time date of the birth of unix> by 0".

**Comment by Thaodan** [comment]
Could you look into this?

**Comment by progval** [comment]
Could you show me your raw IRC logs?

**Comment by Thaodan** [comment]
Are ZNC logs enough?

**Comment by progval** [comment]
no, I need to know what exactly M51 is sending to your client

**Comment by progval** [comment]
actually I could use both the logs between M51 and ZNC, and between ZNC and your client. This might be a bug in ZNC too

**Comment by Thaodan** [comment]
How could there be a bug in znc when the other irc client is fine? The error so far comes from the topic being empty I think.

**Comment by progval** [comment]
Could be

**Comment by Thaodan** [comment]
[ircdebug.log](https://github.com/progval/matrix2051/files/13693620/ircdebug.log)

There you go ^

**Comment by progval** [comment]
I assume `S` is what circe receives from ZNC, `E` is how circe parses the incoming messages, and `C` is what circe sends to ZNC.

```
S: :server. 333user.example.com #alien4ports:matrix.example.com 0
E: "333" "server." "user.example.com" "#alien4ports:matrix.example.com" "0"
```

```
S: :server. 333user.example.com #ci-log:matrix.example.comuser.example.com 1604673997    
E: "333" "server." "user.example.com" "#ci-log:matrix.example.com" "user.example.com" "1604673997"
```

What's going on here? Spaces are missing, but circe manages to parse correctly nonetheless??? Also the first one is missing the third parameter (nick). Could I see the other log I requested?

**Comment by Thaodan** [comment]
The spaces where missing when I cleaned up the log from private information.

The line should look like this:
```
S: :server. 333 user:matrix.example.com #channel:matrix.example.com 0
E: "333" "server." "user:matrix.example.com" "#channel:matrix.example.com" "0"
````

**Comment by Thaodan** [comment]
Logging the connection between ZNC and Matrix 2051:
```
[2023-12-16 21:44:54.504788] (admin@odin/JollaMatrix) ZNC -> CLI [:server. 333  user:matrix.example.com #channel:matrix.example.com 0]
```

**Comment by progval** [comment]
Are you sure that's not between ZNC and the client? `ZNC -> CLI` seems to imply it is

**Comment by Thaodan** [comment]
Oh yeah, moment I have the full log right here/

**Comment by Thaodan** [comment]
[znc.log](https://github.com/progval/matrix2051/files/13693848/znc.log)

**Comment by progval** [comment]
Looks like a bug in ZNC. Reported here: https://github.com/znc/znc/issues/1889

**Comment by Thaodan** [comment]
Thank you.

How does the Matrix2051 respond to clients sending PRIVMSG and ctcp to detect lag?
I noticed that circe disconnects when I use lagmon which does it by sending a PRIVMSG and measuring the time it took to send the message to the server.

https://github.com/emacs-circe/circe/blob/master/circe-lagmon.el#L142

**Comment by progval** [comment]
It probably tries to send it as a regular message to Matrix, which might be rejected by the Matrix server

**Comment by Thaodan** [comment]
Do ctcp requests translate to Matrix in any case?

**Comment by progval** [comment]
Nope, it's going to be a regular Matrix message with `\x01` characters at the beginning and end

**Comment by Thaodan** [comment]
Should that be handled? E.g. for CTCP `VERSION` or `PING`.

**Comment by progval** [comment]
yeah I think they should simply be dropped
