### ISSUE TITLE
Error with resolving hex dependencies !

### ISSUE THREAD

**Issue by raymand211092** [progval/matrix2051#59]
root@srv112118-206152:~/matrix2051# elixir --version
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
root@srv112118-206152:~/matrix2051# MIX_ENV=prod mix deps.get
Resolving Hex dependencies...
** (UndefinedFunctionError) function Logger.__should_log__/2 is undefined or private. Did you mean one of:

      * __should_log__/1

    (logger) Logger.__should_log__(:debug, Hex.Solver.Solver)
    (hex) lib/hex/solver/solver.ex:169: Hex.Solver.Solver.add_incompatibility/2
    (hex) lib/hex/solver/solver.ex:19: Hex.Solver.Solver.run/4
    (hex) lib/hex/solver.ex:53: Hex.Solver.run/5
    (hex) lib/hex/remote_converger.ex:114: Hex.RemoteConverger.run_solver/5
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
root@srv112118-206152:~/matrix2051#

**Comment by progval** [comment]
This looks like an issue in Hex itself; possibly because it is too new/old for your Elixir/OTP version
